### ISSUE TITLE
JavaScript error: $detailModal.find is not a function

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30434]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/68cb8e72-f55c-4fa0-91bc-4b6167f429d2)
click details button, you will see this error
caused by #30115

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by silverwind** [comment]
My bad, should have seen this during review.
