### ISSUE TITLE
Error (HTTP 404) When Assigning Teams to Repos

### ISSUE THREAD

**Issue by ghost** [go-gitea/gitea#20658]
### Description

Since Gitea 1.17.0, normal users cannot assign organization teams to organization repositories. This task can currently only be done by administrators.

Instead of search results, the search box shows the error message "There was an issue querying the server" (see attached screenshot). The web developer console shows that the query to `/org/<organization>/teams/-/search?q=test` returns HTTP 404.

I would expect to at least see all groups that I'm assigned to.

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

![screenshot](https://user-images.githubusercontent.com/80833648/182649346-ea12ae1e-1559-4303-8660-74e74501a57d.png)

### How are you running Gitea?

Self-hosted.

**Comment by rtpt-jonaslieb** [comment]
The cause appears to a change introduced in #19318. More specifically, authorization checks for `/{org}/teams/-/search` (defined [here](https://github.com/go-gitea/gitea/blob/51c8c0f3feb6b71ff5bf45e9e1422f2428eb7f5f/routers/web/web.go#L640)) are tighter than they used to be with the `/api/v1/...` endpoint.

In [this line](https://github.com/go-gitea/gitea/blob/51c8c0f3feb6b71ff5bf45e9e1422f2428eb7f5f/routers/web/web.go#L691) `Context.OrgAssignment(...)` is called with the parameters `requireMember` and `requireOwner`. I'm not sure whether the original intention was "require membership OR ownership" or "require membership AND ownership", but normal members are sorted out in [this line](https://github.com/go-gitea/gitea/blob/51c8c0f3feb6b71ff5bf45e9e1422f2428eb7f5f/modules/context/org.go#L113).

**Comment by lunny** [comment]
What did you mean `normal user`? This interface should be visited only by orgniazation owner team members or repository's admin collobrators.

**Comment by rtpt-jonaslieb** [comment]
Sorry, I should have specified: With `normal user` I meant repository admin collaborators who are not organization owners.

**Comment by lunny** [comment]
Looks like it's a regression from #19318

**Comment by lunny** [comment]
The problem is should the admin permission collaborator of organization repositories can visit organization's users list. If this collaborator is not a member of this organization. I think it's difficult to say it could. But he can visit public users list.

**Comment by deimosOmegaChan** [comment]
I have found the same issue with the version 1.21.10 of gitea.

I have checked this checkbox at the organisation settings.

![image](https://github.com/go-gitea/gitea/assets/26299054/0dd8569e-f1c1-4aec-8d3a-1bb7a1badc72)

user1 is not a member of the team owner.

user1 cannot use autocomplete to assign a team

![image](https://github.com/go-gitea/gitea/assets/26299054/c045fee2-2213-473e-a16b-e2e90d63a7bc)

user1 is able to assign any teams to the repository, which exists inside the organisation. user1 needs only to write the whole name of the team.

Is that a bug or a feature?
