### PR TITLE
Update User information in Gitea based on LDAP when login

### LINKED ISSUE #1359: LDAP - setting user as admin (via objectclass) makes them admin forever  - saves the setting into database.
- Gitea version (or commit ref): master
- Git version:
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I'm using LDAP authentication with correct user and admin objectClass filters.
When user logs in for the first time, if they match the admin filter - they are set as admin in the database forever.

I would expect it to be always dynamically controlled via LDAP - not using the value stored in DB.

I don't expect to be able to control this using admin interface -> users (that should probably have the "administrator" column greyed out.

I DO see that upon each login the value is being checked with ldap - but not used...

### PR DESCRIPTION
**Pull request by DblK**
Currently setting an admin in ldap stay forever, this fix it.
It will close #1359 and related to #1478.

### CODE REVIEW

**Comment by strk** [comment]
LGTM

File: models/login_source.go [hunk 1]
```diff
@@ -416,6 +416,18 @@ func LoginViaLDAP(user *User, login, password string, source *LoginSource, autoR
...
+	// Update User if exist
+	isExist, err := IsUserExist(0, sr.Username)
+	if err != nil {
+		return nil, err
+	} else if isExist {
+		user.LowerName = strings.ToLower(sr.Username)
+		user.Name = sr.Username
+		user.FullName = composeFullName(sr.Name, sr.Surname, sr.Username)
+		user.Email = sr.Mail
+		user.IsAdmin = sr.IsAdmin
```
Comment (lafriks) [inline models/login_source.go]: If no admin filter is set in LDAP source this will remove admin rights when set manually. See check in LDAP sync code: https://github.com/go-gitea/gitea/blob/524885dd6502570dddf5c83f171ee74890dba5c4/models/user.go#L1415

**Review by lafriks — CHANGES_REQUESTED** [review]

File: models/login_source.go [hunk 2]
```diff
@@ -416,6 +416,18 @@ func LoginViaLDAP(user *User, login, password string, source *LoginSource, autoR
 		return nil, ErrUserNotExist{0, login, 0}
 	}
 
+	// Update User if exist
+	isExist, err := IsUserExist(0, sr.Username)
+	if err != nil {
+		return nil, err
+	} else if isExist {
+		user.LowerName = strings.ToLower(sr.Username)
```
Comment (lafriks) [inline models/login_source.go]: As users are searched in LDAP by username there is no need to update LowerName and Name fields for user. If it will change in LDAP, new user will be created anyway

Comment (DblK) [reply models/login_source.go]: Good point, I will fix that

File: models/login_source.go (hunk 1 above)
Comment (DblK) [reply models/login_source.go]: Good point. I will fix that

**Comment by lafriks** [comment]
BTW have you tested this code and are sure it does change anything? As later in the code variable user is assigned to new User struct instance that takes values from ldap search results directly or maybe I'm just missing something here. Very strange code :)

**Comment by DblK** [comment]
Yes I tested it and use it. It work like a charm ;)
I agree to the weird code.

I tested this way:
- connect with a user not present in gitea
- update ldap to add admin role
- logout/login and see if admin is there
- update ldap to remove admin role
- logout/login and see that admin is no more here

The end of the code does update from ldap but the CreateUser function will throw an error and so the User won't be updated. That is why I have do this that way.

**Comment by bkcsoft** [comment]
Does it check while logged in? Otherwise admins needs to flush the sessions when they change the LDAP-settings.  
Does it check API-tokens? Otherwise admins will need to manually remove API-tokens for the same reason.

**Comment by DblK** [comment]
1) I don't think actually there is a "cron" while using gitea to check if something changed. So no, there is no check. So admin has to flush.
2) It does not check the token. That's a good point. Should we remove all tokens? I suggest to make another PR for that.
In function, "[SyncExternalUsers](https://github.com/go-gitea/gitea/blob/master/models/user.go#L1329)", there is no sync for tokens.
So another should modify this one (once merged) and the function too.

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

File: models/login_source.go [hunk 3]
```diff
@@ -416,6 +416,19 @@ func LoginViaLDAP(user *User, login, password string, source *LoginSource, autoR
 		return nil, ErrUserNotExist{0, login, 0}
 	}
 
+	// Update User if exist
+	isExist, err := IsUserExist(0, sr.Username)
+	if err != nil {
+		return nil, err
+	} else if isExist {
+		user.FullName = composeFullName(sr.Name, sr.Surname, sr.Username)
```
Comment (lunny) [inline models/login_source.go:411]: It seems it doesn't update the information to database?

**Comment by strk** [comment]
@DblK what's the destiny of this PR ? :)

**Comment by DblK** [comment]
@strk, It can be merged from my perspective. Not too much time to make modifications if wanted.

**Comment by strk** [comment]
@lafriks were your issues addressed ?

**Comment by lafriks** [comment]
@strk still have to verify that user information is actually updated in database

**Comment by lafriks** [comment]
@bkcsoft I hope you don't mind I changed back that edge as it's binary is used for docker image. To see if code compiles on 1.8 I changed build with no gcc step to :1.8

**Comment by DblK** [comment]
Still need some work on it?

**Comment by tboerger** [comment]
What's the status? I would like to see that merged.

**Comment by lunny** [comment]
conflicted

**Comment by 6543** [comment]
@DblK can you resolve the conflict?

**Comment by DblK** [comment]
Conflict resolved ;)

**Comment by guillep2k** [comment]
It's not building. 😞

**Comment by 6543** [comment]
```
# code.gitea.io/gitea/models
--
3 | models/login_source.go:452:6: no new variables on left side of :=
```

**Comment by 6543** [comment]
+ `...verify that user information is actually updated in database...`

File: models/login_source.go (hunk 3 above)
Comment (DblK) [reply models/login_source.go:411]: See line 418

**Comment by DblK** [comment]
@6543 It should be good now. It's been more than two year on this PR, I could not remember it very well.
I hope I did what you were looking for.

**Comment by guillep2k** [comment]
Still not building. 😞 
```
# code.gitea.io/gitea/models
models/login_source.go:418:16: cannot use user (type *User) as type Engine in argument to updateUserCols:
	*User does not implement Engine (missing Asc method)
models/login_source.go:418:23: cannot use "full_name" (type string) as type *User in argument to updateUserCols
make: *** [Makefile:361: gitea] Error 2
```

File: models/login_source.go [hunk 4]
```diff
@@ -403,6 +403,20 @@ func LoginViaLDAP(user *User, login, password string, source *LoginSource, autoR
...
+		user.Email = sr.Mail
+		// Change existing admin flag only if AdminFilter option is set
+		if len(source.LDAP().AdminFilter) > 0 {
+			user.IsAdmin = sr.IsAdmin
+		}
+	}
```
Comment (6543) [inline models/login_source.go:418]:
```suggestion
	UpdateUserCols(user, "full_name", "email", "is_admin")
	}
```

File: models/login_source.go [hunk 5]
```diff
@@ -403,6 +403,20 @@ func LoginViaLDAP(user *User, login, password string, source *LoginSource, autoR
...
+	updateUserCols(user, "full_name", "email", "is_admin")
```
Comment (6543) [inline models/login_source.go]:
```suggestion
```

**Comment by 6543** [comment]
@DblK this should do it :D

**Comment by DblK** [comment]
Perfect.

**Comment by 6543** [comment]
@DblK I mean the change requests fix the CI and move UpdateUserCols to the right position ... pleace apply ... :D

**Comment by DblK** [comment]
@6543 done ;)

File: models/login_source.go [hunk 6]
```diff
@@ -403,6 +403,20 @@ func LoginViaLDAP(user *User, login, password string, source *LoginSource, autoR
...
+	if err != nil {
+		return nil, err
+	} else if isExist {
+		user.FullName = composeFullName(sr.Name, sr.Surname, sr.Username)
+		user.Email = sr.Mail
+		// Change existing admin flag only if AdminFilter option is set
+		if len(source.LDAP().AdminFilter) > 0 {
+			user.IsAdmin = sr.IsAdmin
+		}
+	UpdateUserCols(user, "full_name", "email", "is_admin")
```
Comment (guillep2k) [inline models/login_source.go]:
```suggestion
		UpdateUserCols(user, "full_name", "email", "is_admin")
```
Let's see if this change fixes the fmt. Otherwise you'll have to pull the current version to your local server, run `make fmt` and push your results back.

Comment (6543) [reply models/login_source.go]: @DblK sory my diff didn't take care of fmt "indent" @guillep2k thanks :D

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
only `go fmt` so approved

File: models/login_source.go [hunk 7]
```diff
@@ -403,6 +403,20 @@ func LoginViaLDAP(user *User, login, password string, source *LoginSource, autoR
...
 
+	// Update User if exist
+	isExist, err := IsUserExist(0, sr.Username)
+	if err != nil {
+		return nil, err
+	} else if isExist {
+		user.FullName = composeFullName(sr.Name, sr.Surname, sr.Username)
+		user.Email = sr.Mail
+		// Change existing admin flag only if AdminFilter option is set
+		if len(source.LDAP().AdminFilter) > 0 {
```
Comment (lunny) [inline models/login_source.go:414]: Should a LDAP administrator automatically be an admin of Gitea?

Comment (guillep2k) [reply models/login_source.go:414]: > 
> 
> Should a LDAP administrator automatically be an admin of Gitea?

https://docs.gitea.io/en-us/authentication/ 😉 
> Admin Filter (optional)
>    An LDAP filter specifying if a user should be given administrator privileges. If a user account passes the filter, the user will be privileged as an administrator.

Comment (lunny) [reply models/login_source.go:414]: OKay! Missed that document.

**Comment by 6543** [comment]
@DblK thx
@lafriks ready to review

**Comment by lunny** [comment]
CI still failed.

**Comment by 6543** [comment]
@DblK is it OK if i picup this PR to get it done?

File: models/login_source.go [hunk 8]
```diff
@@ -403,6 +403,20 @@ func LoginViaLDAP(user *User, login, password string, source *LoginSource, autoR
...
+			user.IsAdmin = sr.IsAdmin
+		}
+		UpdateUserCols(user, "full_name", "email", "is_admin")
```
Comment (6543) [inline models/login_source.go:417]:
```suggestion
		err = UpdateUserCols(user, "full_name", "email", "is_admin")
		if err != nil {
			fmt.Errorf("LoginViaLDAP cant update user information")
		}
```

**Review by 6543 — CHANGES_REQUESTED** [review]

**Comment by DblK** [comment]
> @DblK is it OK if i picup this PR to get it done?

Yeah, go for it!

**Comment by 6543** [comment]
this PR continue on #8849 

@lunny can you close this thx
