### ISSUE TITLE
Disabled "Commit changes" button due to JS error `$(...).areYouSure is not a function` 

### ISSUE THREAD

**Issue by bartvdbraak** [go-gitea/gitea#33491]
### Description

After upgrading to 1.23.1 a multitude of users reported having issues with the comment buttons staying disabled.

They also report getting Javascript errors with the following:

```
JavaScript promise rejection: $(...).areYouSure is not a function. Open browser console to see more details.
```

### Browsers tested
 
- Chrome
- Edge

### Gitea Version

1.23.1 built with GNU Make 4.4.1, go1.23.5 : bindata, timetzdata, sqlite, sqlite_unlock_notify

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Image](https://github.com/user-attachments/assets/66cbccc9-806d-4f2b-b262-e13c123392a2)

![Image](https://github.com/user-attachments/assets/e86080c2-1287-4aab-bcc6-cabc15cba4be)

### Git Version

2.47.2

### Operating System

Ubuntu 24.04

### How are you running Gitea?

Docker Compose with source of truth at https://github.com/blender/gitea

### Database

PostgreSQL

**Comment by bartvdbraak** [comment]
A different error reported by another user:

![Image](https://github.com/user-attachments/assets/21fcdfee-9fbf-4596-9f28-da2ee18d035c)

**Comment by wxiaoguang** [comment]
These 2 problems are different.

For the first one: it seems that the call to `$(...).areYouSure` fails. I have no idea how/why it would happen at the moment.
Because the `areYouSure` should have been there by `initGlobalFormDirtyLeaveConfirm` -> `initAreYouSure`.
Are you using customized JS scripts?

For the second one: it seems that a wrong request is posted to the server (or server responds 404 error due to some unknown reasons).


Do you have ideas about how to reproduce?

**Comment by bartvdbraak** [comment]
> These 2 problems are different.
> 
> For the first one: it seems that the call to `$(...).areYouSure` fails. I have no idea how/why it would happen at the moment. Because the `areYouSure` should have been there by `initGlobalFormDirtyLeaveConfirm` -> `initAreYouSure`. Are you using customized JS scripts?
> 
> For the second one: it seems that a wrong request is posted to the server (or server responds 404 error due to some unknown reasons).
> 
> Do you have ideas about how to reproduce?

I will follow up with the users on this, thanks.

**Comment by wxiaoguang** [comment]
For the `$(...).areYouSure`: if the call fails, then JS stops execution, then the form button can't be enabled.
ps: Have you made changes to the JS code? Or are you using customized JS scripts?


For the second one (JSON error 404, I thought I have seen it .....): figuring out the URL&Request will be helpful.

**Comment by bartvdbraak** [comment]
@wxiaoguang I think you might be right that it has to do with some custom scripts or browser add-ons. I am personally not able to reproduce the issue. I removed the second comment due to it being a different issue than the one described above.

The main issue that remains is:

![Image](https://github.com/user-attachments/assets/b5431e1a-6160-490a-a255-9d13b7ba4b92)

This `Commit changes` staying disabled.

I will do some further digging to see if that is user error.

**Comment by bartvdbraak** [comment]
Figured out that the above seems to be a permission issue. Thanks for your insights.

Will confirm with user and follow up or close this issue.

**Comment by bartvdbraak** [comment]
Confirmed to be an error on user end.
