### ISSUE TITLE
Post a review comment on pull request files view frontend error.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#20809]
regression from #20393 
```log
Uncaught (in promise) TypeError: el.getAttribute is not a function
    at initTooltip (tippy.js:26:22)
    at repo-diff.js:56:16
    at Generator.next (<anonymous>)
    at fulfilled (repo-common.js:108:1)
```
