### ISSUE TITLE
Editing files hangs up with Chrome

### ISSUE THREAD

**Issue by markusschaefer** [go-gitea/gitea#20686]
### Description

After Upgrading to 1.17.0 the file editor hangs up after pressing the button edit.

monaco.js:38 Uncaught (in promise) TypeError: t.hmd is not a function
    at ./node_modules/monaco-editor/esm/vs/base/common/marked/marked.js (monaco.js:38:38532)
    at jt (index.js?v=95cfeb8746010d271b9adf778c18dbad:7:127920)
    at ./node_modules/monaco-editor/esm/vs/editor/browser/core/markdownRenderer.js (monaco.js:91:26551)
    at jt (index.js?v=95cfeb8746010d271b9adf778c18dbad:7:127920)
    at ./node_modules/monaco-editor/esm/vs/editor/contrib/hover/markdownHoverParticipant.js (monaco.js:289:130500)
    at jt (index.js?v=95cfeb8746010d271b9adf778c18dbad:7:127920)
    at ./node_modules/monaco-editor/esm/vs/editor/contrib/hover/hover.js (monaco.js:289:99382)
    at jt (index.js?v=95cfeb8746010d271b9adf778c18dbad:7:127920)
    at ./node_modules/monaco-editor/esm/vs/editor/contrib/colorPicker/colorContributions.js (monaco.js:226:9275)
    at jt (index.js?v=95cfeb8746010d271b9adf778c18dbad:7:127920)

### Gitea Version

1.17.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://user-images.githubusercontent.com/63106567/183081902-71cde209-18f2-4635-8fcd-45df1031fa4c.png)

### How are you running Gitea?

docker image gitea/gitea:1.17.0

### Database

PostgreSQL

**Comment by markusschaefer** [comment]
Firefox is working fine

**Comment by silverwind** [comment]
Likely a browser cache issue, try a hard page reload (ctrl-shift-r)

**Comment by silverwind** [comment]
Definitely a cache issue. https://github.com/go-gitea/gitea/pull/18632 will eventually fix it.
