### PR TITLE
Fix tooltip init after review

### LINKED ISSUE #20809: Post a review comment on pull request files view frontend error.
regression from #20393 
```log
Uncaught (in promise) TypeError: el.getAttribute is not a function
    at initTooltip (tippy.js:26:22)
    at repo-diff.js:56:16
    at Generator.next (<anonymous>)
    at fulfilled (repo-common.js:108:1)
```

### PR DESCRIPTION
**Pull request by silverwind**
Previous code passed a jQuery collection which `initTooltip` couldn't handle. Instead, iterate the individial matched elements and add a dollar to the variable name to make it clear it's jQuery.

Fixes: https://github.com/go-gitea/gitea/issues/20809

### CODE REVIEW

**Review by Gusted — APPROVED** [review]

**Comment by silverwind** [comment]
I also renamed `form` to `$form` for clarity, which then made eslint hit on `jquery/no-serialize`, so I replaced `$form.serialize` with the modern vanilla js equivalent.

**Review by lafriks — APPROVED** [review]
