### ISSUE TITLE
Can't build gitea on Windows (undefined: syscall.Kill)

### ISSUE THREAD

**Issue by lukbukkit** [go-gitea/gitea#8544]
- Gitea version (or commit ref): 167e8f18da3aadcdcdd7bb8c488c39d73ac65803
- Git version: `git version 2.23.0.windows.1`
- Go version: `go version go1.13.1 windows/amd64`
- Operating system: Windows 10 1903
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant

## Description
When trying to build Gitea under Windows 10 I get this error:

I guess the error is caused by the fact that the methods of the Go package [`syscall`](https://golang.org/pkg/syscall/) are platform dependent. See [syscall_windows.go](https://golang.org/src/syscall/syscall_windows.go), there is no `Kill` method. The code which breaks my build was introduced with #7274.

```
# code.gitea.io/gitea/modules/graceful
modules\graceful\server.go:112:7: undefined: syscall.Kill
modules\graceful\server.go:158:7: undefined: syscall.Kill
modules\graceful\server_signals.go:22:3: undefined: syscall.SIGUSR1
modules\graceful\server_signals.go:23:3: undefined: syscall.SIGUSR2
modules\graceful\server_signals.go:26:3: undefined: syscall.SIGTSTP
modules\graceful\server_signals.go:57:8: undefined: syscall.SIGUSR1
modules\graceful\server_signals.go:59:8: undefined: syscall.SIGUSR2
modules\graceful\server_signals.go:68:8: undefined: syscall.SIGTSTP
```

The build works fine with the commit 4a290bd6.

**Comment by zeripath** [comment]
Fixed by #8537

**Comment by LukBukkit** [comment]
Thanks a lot!
